import React from 'react'
import Head from 'next/head'

const Header = () => {
  return (
    <>
      <Head>
        <meta charSet='UTF-8' />
        <meta
          name='viewport'
          content='width=device-width, height=device-height, initial-scale=1.0'
        />
        <title>TITILE</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Coda:wght@400;800&family=Fira+Code:wght@300&family=Montserrat:wght@900&display=swap'
          rel='stylesheet'
        />
      </Head>
    </>
  )
}

export default Header
